DROP TABLE IF EXISTS Card_Types;
DROP TABLE IF EXISTS Card_Subtypes;
DROP TABLE IF EXISTS Colors;
DROP TABLE IF EXISTS Types;
DROP TABLE IF EXISTS Subtypes;
DROP TABLE IF EXISTS Cards;
DROP TABLE IF EXISTS Sets;

CREATE TABLE Colors (
	 ColorID INT AUTO_INCREMENT
	,Color VARCHAR(10)
	,PRIMARY KEY (ColorID)
);

CREATE TABLE Types (
	 TypeID INT AUTO_INCREMENT
	,TypeDesc VARCHAR(50)
	,PRIMARY KEY (TypeID)
);

CREATE TABLE Subtypes (
	 SubtypeID INT AUTO_INCREMENT
	,SubtypeDesc VARCHAR(50)
	,PRIMARY KEY (SubtypeID)
);

CREATE TABLE Sets (
	 SetID INT AUTO_INCREMENT
	,SetCode VARCHAR(10)
	,SetName VARCHAR(100)
	,PRIMARY KEY (SetID)
);

CREATE TABLE Cards (
	 CardID INT AUTO_INCREMENT
	,CMC INT
	,ManaCost VARCHAR(10)
	,NAME VARCHAR(100)
	,Power VARCHAR(10)
	,Rarity VARCHAR(20)
	,SetID INT
	,Text VARCHAR(4000)
	,Toughness VARCHAR(10)
	,PRIMARY KEY (CardID)
);

CREATE TABLE Card_Types (
	 CTypeID INT AUTO_INCREMENT
	,CardID INT
	,TypeID INT
	,PRIMARY KEY (CTypeID)
	,FOREIGN KEY (CardID) REFERENCES Cards(CardID)
	,FOREIGN KEY (TypeID) REFERENCES Types(TypeID)
);

CREATE TABLE Card_Subtypes (
	 CSubtypeID INT AUTO_INCREMENT
	,CardID INT
	,SubtypeID INT
	,PRIMARY KEY (CSubtypeID)
	,FOREIGN KEY (CardID) REFERENCES Cards(CardID)
	,FOREIGN KEY (SubtypeID) REFERENCES Subtypes(SubtypeID)
);
